---
global:
  image:
    name: nexus-docker-public-hosted.ossim.io/omar-prestager
    pullPolicy: Always
  replicas: 5
  storage:
    pvc:
      name: omar-oms-ossim-data-pvc
#  namespace: omar-dev
  namespace: omar-3pa-dev
#  ingress:
#    host: omar-prestager.ossim.io
#    loadBalancer: aaac6bc42260c4b60a9e580e4febc19f-e69fe95399e829a2.elb.us-east-1.amazonaws.com
  database:
    name: o2_omar_db
    username: postgres
    password: 'qKcSn=3G|3~54*gO'
    host: omar-3pa-dev-aurora-rdsdbcluster-nzw5yqvz2wso.cluster-cfussmnw2zzg.us-east-1.rds.amazonaws.com
    port: 5432
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi