apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: omar-prestager
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/omar-prestager
    jib: {}
deploy:
  helm:
    releases:
    - name: omar-prestager
      chartPath: chart
      artifactOverrides:
        image: nexus-docker-public-hosted.ossim.io/omar-prestager