apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: omar-prestager
build:
  artifacts:
  - image: nexus-docker-private-hosted.ossim.io/omar-prestager
    jib: {}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: omar-prestager
      chartPath: chart
      valuesFiles:
        - chart/values-dev.yaml
      # This override is used to pass skaffold's rebuilt image to
      # imageName in the helm chart deployment.yaml.
      # If you want to use an existing image rather than skaffold's
      # comment this out and specify the image in the values-dev.yaml
      artifactOverrides:
        imageSkaffoldOverride: nexus-docker-private-hosted.ossim.io/omar-prestager
