apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}"
  labels:
    app: "{{ .Values.appName }}"
data:
  application.yaml: |-
    omar:
      prestager:
      {{ include "geoscript-footprint-cleanup.dbInfo" . }}
      index:
        stagerAddress: http://${OMAR_STAGER_APP_SERVICE_HOST}:${OMAR_STAGER_APP_SERVICE_PORT}/omar-stager