---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    app:  {{ .Chart.Name }}
data:
  application.yml: |-
    omar:
      prestager:
        database:
          name: {{ .Values.global.database.name }}
          username: {{ .Values.global.database.username }}
          password: {{ .Values.global.database.password }}
          host: {{ .Values.global.database.host }}
          port: {{ .Values.global.database.port }}
        index:
          stagerAddress: http://${OMAR_STAGER_APP_SERVICE_HOST}:${OMAR_STAGER_APP_SERVICE_PORT}/omar-stager
