apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}"
  labels:
    app: "{{ .Values.appName }}"
data:
  application.yaml: |-
    omar:
      prestager:
        database:
          name: {{ .Values.database.name }}
          username: {{ .Values.database.user }}
          password: {{ .Values.database.password }}
          host: {{ .Values.database.host }}
          port: {{ .Values.database.port }}
      index:
        stagerAddress: http://${OMAR_STAGER_APP_SERVICE_HOST}:${OMAR_STAGER_APP_SERVICE_PORT}/omar-stager