apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
#        - mountPath: /System/Volumes/Data/ossim
#          name: input
#        - mountPath: /data
#          name: ossim-data
        - mountPath: /data
          name: ossim-data
        - mountPath: /maxar-blacksky-data
          name: maxar-blacksky-data
        - mountPath: /maxar-skysat-data
          name: maxar-skysat-data
        - mountPath: /gegd-dem-tiled
          name: gegd-dem-tiled
      volumes:
      - name: scratch-volume
        emptyDir: {}
#      - name: input
#        hostPath:
#          path: /System/Volumes/Data/ossim
#      - name: ossim-data
#        persistentVolumeClaim:
#          claimName: {{ .Values.global.storage.pvc.name }}
      - name: ossim-data
        persistentVolumeClaim:
          claimName: omar-oms-ossim-data-pvc
      - name: maxar-blacksky-data
        persistentVolumeClaim:
          claimName: omar-oms-maxar-blacksky-data-pvc
      - name: maxar-skysat-data
        persistentVolumeClaim:
          claimName: omar-oms-maxar-skysat-data-pvc
      - name: gegd-dem-tiled
        persistentVolumeClaim:
          claimName: omar-wms-lite-gegd-dem-tiled-pvc


